"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight } from "lucide-react";

type Kind = "terms" | "privacy" | "refunds" | "contact";
const copy = {
  terms: {
    en: { title: "Terms of use", intro: "These draft terms explain the basic rules for browsing 7ZMA and placing a digital-product order.", headings: ["Orders and confirmation", "Product details", "Payment and delivery", "Availability and changes"], body: ["Submitting an order is a request for the store team to review it. An order is not confirmed until the team contacts you and confirms availability, final price, payment instructions, and delivery details.", "Digital products can be region-specific, edition-specific, or delivered in different ways. Review the product page and ask the store before ordering if anything is unclear.", "The store does not collect online payment through this site. Payment is arranged manually after order review. Do not send payment until the store confirms the order and its instructions.", "Products, prices, payment methods, and delivery estimates can change. If the store cannot fulfill an order, its team will contact you to discuss next steps."], label: "Draft for owner review" },
    ar: { title: "شروط الاستخدام", intro: "توضح هذه المسودة القواعد الأساسية لتصفح 7ZMA وإرسال طلب منتج رقمي.", headings: ["الطلبات والتأكيد", "تفاصيل المنتجات", "الدفع والتسليم", "التوفر والتغييرات"], body: ["إرسال الطلب يعني طلب مراجعته من فريق المتجر. لا يُعد الطلب مؤكداً حتى يتواصل الفريق معك ويؤكد التوفر والسعر النهائي وتعليمات الدفع والتسليم.", "قد ترتبط المنتجات الرقمية بمنطقة أو إصدار محدد، وقد تختلف طريقة تسليمها. راجع صفحة المنتج واسأل المتجر قبل الطلب إن كانت هناك نقطة غير واضحة.", "لا يجمع هذا الموقع المدفوعات إلكترونياً. يتم ترتيب الدفع يدوياً بعد مراجعة الطلب. لا ترسل أي مبلغ قبل تأكيد المتجر للطلب وتعليماته.", "قد تتغير المنتجات والأسعار وطرق الدفع وتقديرات التسليم. إذا تعذر تنفيذ الطلب، سيتواصل معك فريق المتجر لمناقشة الخطوات التالية."], label: "مسودة لمراجعة مالك المتجر" },
  },
  privacy: {
    en: { title: "Privacy notice", intro: "This draft describes information used to review and fulfill store orders. It should be checked against the store’s actual practices before publication.", headings: ["Information you provide", "How information is used", "Retention and requests", "Service providers"], body: ["An order may include your name, WhatsApp number, order contents, selected currency, and an optional note. Account sign-in may also process your email and username.", "The store uses order details to review your request, contact you about confirmation and delivery, prevent abuse, and maintain store records. This site does not process online payments.", "Order records may be retained for operational and security purposes. You can contact the store to ask about access, correction, or deletion, subject to records the store needs to maintain.", "The store may rely on hosting, database, authentication, and bot-protection providers to operate the service. The owner should document the providers and retention settings actually in use."], label: "Draft for owner review" },
    ar: { title: "إشعار الخصوصية", intro: "تشرح هذه المسودة المعلومات المستخدمة لمراجعة الطلبات وتنفيذها. يجب مطابقتها مع ممارسات المتجر الفعلية قبل النشر.", headings: ["المعلومات التي تقدمها", "كيفية استخدام المعلومات", "الاحتفاظ بالبيانات والطلبات", "مقدمو الخدمة"], body: ["قد يتضمن الطلب اسمك ورقم واتساب ومحتويات الطلب والعملة المختارة وملاحظة اختيارية. وقد يعالج تسجيل الدخول بيانات بريدك الإلكتروني واسم المستخدم.", "يستخدم المتجر تفاصيل الطلب لمراجعته والتواصل بشأن التأكيد والتسليم ومكافحة إساءة الاستخدام والاحتفاظ بسجلات المتجر. لا يعالج هذا الموقع المدفوعات إلكترونياً.", "قد تُحفظ سجلات الطلبات لأغراض التشغيل والأمان. يمكنك التواصل مع المتجر لطلب الوصول إلى بياناتك أو تصحيحها أو حذفها، مع مراعاة السجلات التي يحتاج المتجر إلى الاحتفاظ بها.", "قد يعتمد المتجر على مزودي الاستضافة وقواعد البيانات والمصادقة والحماية من الروبوتات لتشغيل الخدمة. على المالك توثيق المزودين وإعدادات الاحتفاظ المستخدمة فعلياً."], label: "مسودة لمراجعة مالك المتجر" },
  },
  refunds: {
    en: { title: "Delivery and refund policy", intro: "Digital orders need manual review because availability, region, and delivery format may differ by item.", headings: ["Before confirmation", "Delivery", "After delivery", "Need help?"], body: ["The store team checks stock, product details, and the order total before confirming. A submitted request alone does not reserve a product or guarantee delivery.", "Once confirmed, the team provides the expected delivery method and timing. Keep your order number to follow progress on the tracking page.", "Digital goods can be difficult to reverse once a code is revealed or an account is transferred. Contact the store promptly if an item is missing, incorrect, or inaccessible. The owner must review and publish the final refund rules for each product type.", "Use the contact option shown by the store or the order tracking page. Do not include payment credentials in a support message."], label: "Draft for owner review" },
    ar: { title: "سياسة التسليم والاسترداد", intro: "تحتاج الطلبات الرقمية إلى مراجعة يدوية لأن التوفر والمنطقة وطريقة التسليم قد تختلف حسب المنتج.", headings: ["قبل التأكيد", "التسليم", "بعد التسليم", "هل تحتاج إلى مساعدة؟"], body: ["يتحقق فريق المتجر من المخزون وتفاصيل المنتج وإجمالي الطلب قبل تأكيده. إرسال الطلب وحده لا يحجز منتجاً ولا يضمن تسليمه.", "بعد التأكيد، يوضح الفريق طريقة التسليم والوقت المتوقع. احتفظ برقم طلبك لمتابعته في صفحة التتبع.", "قد يصعب التراجع عن المنتجات الرقمية بعد كشف الرمز أو نقل الحساب. تواصل مع المتجر سريعاً إذا كان المنتج مفقوداً أو غير صحيح أو تعذر الوصول إليه. على المالك مراجعة قواعد الاسترداد النهائية ونشرها لكل نوع من المنتجات.", "استخدم وسيلة التواصل التي يعرضها المتجر أو صفحة تتبع الطلب. لا ترسل بيانات الدفع السرية ضمن رسالة الدعم."], label: "مسودة لمراجعة مالك المتجر" },
  },
  contact: {
    en: { title: "Contact 7ZMA", intro: "Questions about a product or an order? Keep your order number handy so the team can help more quickly.", headings: ["Order support", "Before you order", "Safe communication", "Track an order"], body: ["For an existing request, use the tracking page or the WhatsApp contact provided by the store after reviewing your order.", "Check the product’s platform, region, edition, and delivery details. Ask the store for clarification before sending an order if needed.", "The store will never need your account password or one-time sign-in code to confirm an order. Do not include payment credentials in a message.", "The tracking page lets you check an order with its tracking link or the details requested there."], label: "Store contact details will appear when configured" },
    ar: { title: "تواصل مع 7ZMA", intro: "لديك سؤال عن منتج أو طلب؟ جهّز رقم الطلب ليساعدك الفريق بسرعة أكبر.", headings: ["دعم الطلبات", "قبل الطلب", "تواصل آمن", "تتبّع الطلب"], body: ["للطلب الحالي، استخدم صفحة التتبع أو وسيلة واتساب التي يقدمها المتجر بعد مراجعة طلبك.", "راجع المنصة والمنطقة والإصدار وتفاصيل التسليم. اطلب التوضيح من المتجر قبل إرسال الطلب إذا لزم الأمر.", "لن يحتاج المتجر إلى كلمة مرور حسابك أو رمز تسجيل الدخول لمرة واحدة لتأكيد الطلب. لا تضع بيانات الدفع السرية في الرسائل.", "تتيح صفحة التتبع متابعة الطلب عبر رابط التتبع أو البيانات المطلوبة هناك."], label: "تظهر بيانات التواصل بعد إعدادها من المتجر" },
  },
} as const;

export function InformationPage({ kind }: { kind: Kind }) {
  const [locale, setLocale] = useState<"ar" | "en">("ar");
  useEffect(() => { const value = localStorage.getItem("7zma.locale"); setLocale(value === "en" ? "en" : "ar"); }, []);
  const content = copy[kind][locale];
  const BackArrow = locale === "ar" ? ArrowRight : ArrowLeft;
  return <main className="information-page" dir={locale === "ar" ? "rtl" : "ltr"}><Link href="/" className="information-back"><BackArrow size={17} />{locale === "ar" ? "العودة إلى 7ZMA" : "Back to 7ZMA"}</Link><article className="information-card"><p className="checkout-kicker">7ZMA · {kind.toUpperCase()}</p><h1>{content.title}</h1><p className="information-intro">{content.intro}</p><span className="information-review">{content.label}</span><div className="information-sections">{content.headings.map((heading,index)=><section key={heading}><span>0{index+1}</span><div><h2>{heading}</h2><p>{content.body[index]}</p></div></section>)}</div><nav className="information-links"><Link href="/terms">{locale === "ar" ? "الشروط" : "Terms"}</Link><Link href="/privacy">{locale === "ar" ? "الخصوصية" : "Privacy"}</Link><Link href="/refunds">{locale === "ar" ? "التسليم والاسترداد" : "Delivery & refunds"}</Link><Link href="/contact">{locale === "ar" ? "التواصل" : "Contact"}</Link><Link href="/track">{locale === "ar" ? "تتبع طلب" : "Track order"}</Link></nav></article></main>;
}
